apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: acafd2mes-go
  janus-idp.io/tekton: acafd2mes-go
  backstage.io/kubernetes-id: acafd2mes-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: acafd2mes-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
