apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: acafd2mes-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: acafd2mes-go 
  name: acafd2mes-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: acafd2mes-go 
